openapi: '3.0.3'
info:
  title: Sample API
  version: '1.0'

paths:
  /user/{uid}:
    get:
      operationId: GetUserById
      description: ユーザー情報を取得する
      parameters:
        - name: uid
          in: path
          required: true
          schema:
            type: integer
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        default:
          description: Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DefaultErrorResponse'
  /users:
    get:
      operationId: GetUser
      description: ユーザー情報を取得する
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        default:
          description: Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DefaultErrorResponse'
    post:
      operationId: PostUser
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
      responses:
        "200":
          description: OK
        default:
          description: エラー
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DefaultErrorResponse'

components:
  schemas:
    User:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
      required:
        - id
        - name
    DefaultErrorResponse:
      type: object
      properties:
        message:
          type: string
